export const themes = [
  { value: 'abbott', label: 'Abbott' },
  { value: 'abcdef', label: 'ABCDEF' },
  { value: 'ambiance-mobile', label: 'Ambiance Mobile' },
  { value: 'ambiance', label: 'Ambiance' },
  { value: 'ayu-dark', label: 'Ayu Dark' },
  { value: 'ayu-mirage', label: 'Ayu Mirage' },
  { value: 'base16-dark', label: 'Base16 Dark' },
  { value: 'base16-light', label: 'Base16 Light' },
  { value: 'bespin', label: 'Bespin' },
  { value: 'blackboard', label: 'Blackboard' },
  { value: 'cobalt', label: 'Cobalt' },
  { value: 'colorforth', label: 'Colorforth' },
  { value: 'dracula', label: 'Dracula' },
  { value: 'duotone-dark', label: 'Duo Tone Dark' },
  { value: 'duotone-light', label: 'Duo Tone Light' },
  { value: 'eclipse', label: 'Eclipse' },
  { value: 'elegant', label: 'Elegant' },
  { value: 'erlang-dark', label: 'Erlang Dark' },
  { value: 'gruvbox-dark', label: 'Gruvbox Dark' },
  { value: 'hopscotch', label: 'Hopscotch' },
  { value: 'icecoder', label: 'Icecoder' },
  { value: 'idea', label: 'Idea' },
  { value: 'isotope', label: 'Isotope' },
  { value: 'juejin', label: 'Juejin' },
  { value: 'lesser-dark', label: 'Lesser Dark' },
  { value: 'liquibyte', label: 'Liquibyte' },
  { value: 'lucario', label: 'Lucario' },
  { value: 'material-darker', label: 'Material Darker' },
  { value: 'material-ocean', label: 'Material Ocean' },
  { value: 'material-palenight', label: 'Material Pale Night' },
  { value: 'material', label: 'Material' },
  { value: 'mbo', label: 'Mbo' },
  { value: 'mdn-like', label: 'MDN Like' },
  { value: 'midnight', label: 'Midnight' },
  { value: 'monokai', label: 'Monokai' },
  { value: 'moxer', label: 'Moxer' },
  { value: 'neat', label: 'Neat' },
  { value: 'neo', label: 'Neo' },
  { value: 'night', label: 'Night' },
  { value: 'nord', label: 'Nord' },
  { value: 'oceanic-next', label: 'Oceanic Next' },
  { value: 'panda-syntax', label: 'Panda Syntax' },
  { value: 'paraiso-dark', label: 'Paraiso Dark' },
  { value: 'railscasts', label: 'Railcasts' },
  { value: 'rubyblue', label: 'Ruby Blue' },
  { value: 'seti', label: 'Seti' },
  { value: 'shadowfox', label: 'Shadow Fox' },
  { value: 'solarized', label: 'Solarized' },
  { value: 'twilight', label: 'Twilight' },
  { value: 'xq-dark', label: 'XQ Dark' },
  { value: 'yeti', label: 'Yeti' },
  { value: 'yonce', label: 'Yonce' },
  { value: 'zenburn', label: 'Zenburn' },
]

export const tabSizes = [
  { value: 2, label: 2 },
  { value: 4, label: 4 },
  { value: 6, label: 6 },
  { value: 8, label: 8 },
]

export const languages = [
  { value: 'apl', label: 'APL' },
  { value: 'asn.1', label: 'ASN.1' },
  { value: 'asterisk', label: 'Asterisk' },
  { value: 'brainfuck', label: 'Brainfuck' },
  { value: 'clike', label: 'Clike' },
  { value: 'clojure', label: 'Clojure' },
  { value: 'cmake', label: 'Cmake' },
  { value: 'cobol', label: 'Cobol' },
  { value: 'coffsescript', label: 'CoffeeScript' },
  { value: 'commonlisp', label: 'CommonLisp' },
  { value: 'crystal', label: 'Crystal' },
  { value: 'css', label: 'CSS' },
  { value: 'cypher', label: 'Cypher' },
  { value: 'd', label: 'D' },
  { value: 'dart', label: 'Dart' },
  { value: 'django', label: 'Django' },
  { value: 'dockerfile', label: 'DockerFile' },
  { value: 'dtd', label: 'DTD' },
  { value: 'dylan', label: 'Dylan' },
  { value: 'ebnf', label: 'EBNF' },
  { value: 'ecl', label: 'ECL' },
  { value: 'eiffel', label: 'Eiffel' },
  { value: 'elm', label: 'ELM' },
  { value: 'erlang', label: 'ErLang' },
  { value: 'factor', label: 'Factor' },
  { value: 'fcl', label: 'FCL' },
  { value: 'forth', label: 'Forth' },
  { value: 'fortran', label: 'Fortran' },
  { value: 'gas', label: 'Gas' },
  { value: 'gfm', label: 'Gfm' },
  { value: 'gherkin', label: 'Gherkin' },
  { value: 'go', label: 'Go' },
  { value: 'groovy', label: 'Groovy' },
  { value: 'haml', label: 'Haml' },
  { value: 'handlebars', label: 'HandleBars' },
  { value: 'haskell', label: 'Haskell' },
  { value: 'haskell-literate', label: 'Haskell Literate' },
  { value: 'haxe', label: 'Haxe' },
  { value: 'htmlembedded', label: 'Html Embedded' },
  { value: 'htmlmixed', label: 'Html Mixed' },
  { value: 'http', label: 'Http' },
  { value: 'idl', label: 'Idl' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'jinja2', label: 'Jinja2' },
  { value: 'jsx', label: 'Jsx' },
  { value: 'julia', label: 'Julia' },
  { value: 'livescript', label: 'LiveScript' },
  { value: 'lua', label: 'Lua' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'mathematica', label: 'Mathematica' },
  { value: 'mbox', label: 'Mbox' },
  { value: 'mirc', label: 'Mirc' },
  { value: 'mllike', label: 'MLLike' },
  { value: 'modelica', label: 'Modelica' },
  { value: 'mscgen', label: 'Mscgen' },
  { value: 'mumps', label: 'Mumps' },
  { value: 'nginx', label: 'Nginx' },
  { value: 'nsis', label: 'Nsis' },
  { value: 'ntriples', label: 'Ntriples' },
  { value: 'octave', label: 'Octave' },
  { value: 'oz', label: 'Oz' },
  { value: 'pascal', label: 'Pascal' },
  { value: 'perl', label: 'Perl' },
  { value: 'php', label: 'Php' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'pug', label: 'Pug' },
  { value: 'puppet', label: 'Puppet' },
  { value: 'python', label: 'Python' },
  { value: 'q', label: 'Q' },
  { value: 'r', label: 'R' },
  { value: 'rpm', label: 'Rpm' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'sas', label: 'Sas' },
  { value: 'sass', label: 'Sass' },
  { value: 'scheme', label: 'Scheme' },
  { value: 'shell', label: 'Shell' },
  { value: 'sieve', label: 'Sieve' },
  { value: 'slim', label: 'Slim' },
  { value: 'solr', label: 'Solr' },
  { value: 'soy', label: 'Soy' },
  { value: 'sparql', label: 'Sparql' },
  { value: 'spreadsheet', label: 'Spreadsheet' },
  { value: 'sql', label: 'SQL' },
  { value: 'stex', label: 'Stex' },
  { value: 'stylus', label: 'Stylus' },
  { value: 'swift', label: 'Swift' },
  { value: 'textile', label: 'Textile' },
  { value: 'tornado', label: 'Tornado' },
  { value: 'troff', label: 'Troff' },
  { value: 'ttcn', label: 'Ttcn' },
  { value: 'turtle', label: 'Turtle' },
  { value: 'twig', label: 'Twig' },
  { value: 'vb', label: 'Vb' },
  { value: 'vbscript', label: 'VbScript' },
  { value: 'velocity', label: 'Velocity' },
  { value: 'verilog', label: 'Verilog' },
  { value: 'vhdl', label: 'Vhdl' },
  { value: 'vue', label: 'Vue' },
  { value: 'wast', label: 'Wast' },
  { value: 'webidl', label: 'Webidl' },
  { value: 'xml', label: 'Xml' },
  { value: 'xquery', label: 'Xquery' },
  { value: 'yacas', label: 'Yacas' },
  { value: 'yaml', label: 'Yaml' },
  { value: 'yaml-frontmatter', label: 'Yaml Frontmatter' },
  { value: 'z80', label: 'Z80' },
]
